routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::get('/', [BlogController::class, 'index'])->name('index');
});
Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::match(['get', 'post'],'/search-date', '\App\Http\Controllers\BlogController@searchDate')->name('search-date');

Route::resource('blog', \App\Http\Controllers\BlogController::class);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $table = "blogs";
    protected $guarded = ['id'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'age',
        'type',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $dataBlog = Blog::all();
        $user = User::get(['type']);
        return view('Blogs.index', compact('dataBlog','user'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('Blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->except('_token');
        Blog::create($data);
        return redirect()->route('blog.index');
    }

    public function searchDate(Request $request)
    {

        $date = $request->except('_token');
        //DB::table('fichas')->whereDate('created_at', $fecha)->get();
        $dataBlog = Blog::where('date', $date)->get();
        return view('Blogs.index', compact('dataBlog'));
        
    }
    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('Blogs.edit' , compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Blog $blog)
    {
        $blog->update($request->except('_token','_method'));

        return redirect()->route('blog.index')
            ->with('success', ' Blog Actualizado Satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        $blog = Blog::find($blog->id);
        $blog->delete($blog);
        return redirect()->route('blog.index')
            ->with('success', 'Blog Eliminado Satisfactoriamente');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/Blogs/create.blade.php
@extends('layouts.app')

@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-primary">
   <center><p>{{ $message}}</p></center> 
</div>
@endif
@if(count($errors)>0)
<div class="alert alert-danger" role="alert">
    <ul>
        @foreach($errors->all() as $error)
            <li>{{$error}}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card  border-primary mb-3">
                <div class="card-header border-primary text-center">{{ __('Formulario de Registro del Blog') }}</div>

                <div class="card-body">
                    <form name="fvalida" method="POST" action="{{ route('blog.store') }}">
                        @csrf

                        <div class="row mb-3">
                            <label for="title" class="col-md-4 col-form-label text-md-end">{{ __('Título') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="description" class="col-md-4 col-form-label text-md-end">{{ __('Descripción') }}</label>
                            <div class="col-md-6">
                                <textarea  class="form-control" name="description" id="description" rows="3" value="description">{{old('description')}}</textarea>
                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="date" class="col-md-4 col-form-label text-md-end">{{ __('Fecha') }}</label>
                            <div class="col-md-6">
                                <input id="date" type="date" class="form-control @error('date') is-invalid @enderror" name="date" value="{{ old('date') }}" required autocomplete="date" autofocus>
                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Registrar Blog') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Blogs/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-primary mb-3" style="max-width: 80rem;">
                <div class="card card-default">
                    <div class="card-header border-primary">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <span class="card-title ">Actualizar Blog</span>
                            <a href="{{ route('blog.index') }}" class="btn btn-primary btn-lg active"  role="button" aria-pressed="true">
                                {{ __('Atrás') }}
                            </a>
                        </div> 
                    </div>
                    @if(count($errors)>0)
                    <div class="alert alert-danger" role="alert">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                     @endif
                    <div class="card-body">
                        <form method="POST" action="{{ route('blog.update', $blog->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf
                            <div class="row mb-3">
                                <label for="title" class="col-md-4 col-form-label text-md-end">{{ __('Título') }}</label>
    
                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ isset($blog->title) ? $blog->title : old('title')}}" required autocomplete="title" autofocus>
    
                                    @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="row mb-3">
                                <label for="description" class="col-md-4 col-form-label text-md-end">{{ __('Descripción') }}</label>
                                <div class="col-md-6">
                                    <textarea  class="form-control" name="description" id="description" rows="3" value="description">{{ isset($blog->description) ? $blog->description : old('description')}}</textarea>
                                    @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="row mb-3">
                                <label for="date" class="col-md-4 col-form-label text-md-end">{{ __('Fecha') }}</label>
                                <div class="col-md-6">
                                    <input id="date" type="date" class="form-control @error('date') is-invalid @enderror" name="date" value="{{ isset($blog->date) ? $blog->date : old('date')}}" required autocomplete="date" autofocus>
                                    @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Actualizar Blog') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/Blogs/index.blade.php
@extends('layouts.app')

@section('content')
  @if (Auth::check())
  <div class="container">
    <div class="row">
        <div class="col-md-6">
            <a href="{{route('blog.create')}}" class="btn btn-info"><span class="navbar-brand mb-0 h1">{{ __('Crear Blog') }}</span></a>
            <br>
            <br>
          <div class="card  border-primary mb-3">
            @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <center><p>{{ $message }}</p></center>
              </div>
            @endif
            @foreach ($dataBlog as $blog)
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                        
                <h2 class="accordion-header" id="headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{$blog->title}}
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <strong>{{$blog->title}}</strong> {{$blog->description}} <br><br>
                    <strong>Publicacion: {{$blog->date}}</strong>
                    <!-- Botón de editar el blog -->
                      @if(Auth::user()->type == 1)
                        <a class="btn btn-sm btn-success" href="{{route('blog.edit', $blog->id)}}"><i class="fa fa-fw fa-edit"></i> Editar</a>
                      @endif
                   
                    <!-- Botón de Eliminar el blog-->
                      @if(Auth::user()->type == 1)
                        <form action="{{route('blog.destroy', $blog)}}" method="POST" class="d-inline">                           
                          @csrf
                        {{ method_field('DELETE')}} 
                          <input type="submit" onclick="return confirm('¿Quieres Borrar el Blog?')"                
                          value="Eliminar" class="btn btn-danger" >
                        </form>
                      @endif
                  </div>
                </div>      
              </div>
            </div>
            @endforeach
          </div>
        </div>
        <div class="col-md-6 text-center">
          <div class="card border-primary mb-3" style="max-width: 80rem;" > 
            <form class="form-inline" action="{{route('search-date')}}" method="post">
              @csrf
              <br>
              <label for="form-control" >Seleccione la fecha</label>
              
              <div class="row mb-3">
                <label for="date" class="col-md-4 col-form-label text-md-end">{{ __('Fecha') }}</label>
                <div class="col-md-6">
                    <input id="date" type="date" class="form-control" name="date" required autocomplete="date" autofocus>
                </div>
              </div>
              <button type="submit" class="btn btn-primary mb-2">Buscar</button>
            </form>
          </div>
        </div> 
      </div>
    </div>
  @else
  <div class="container">
    <div class="row">
        <div class="col-md-6">
          <div class="card  border-primary mb-3">
            @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <center><p>{{ $message }}</p></center>
              </div>
            @endif
            @foreach ($dataBlog as $blog)
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                        
                <h2 class="accordion-header" id="headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{$blog->title}}
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <strong>{{$blog->title}}</strong> {{$blog->description}} <br><br>
                    <strong>Publicacion: {{$blog->date}}</strong>
                  </div>
                </div>      
              </div>
            </div>
            @endforeach
          </div>
        </div>
        <div class="col-md-6 text-center">
          <div class="card border-primary mb-3" style="max-width: 80rem;" > 
            <form class="form-inline" action="{{route('search-date')}}" method="post">
              @csrf
              <br>
              <label for="form-control" >Seleccione la fecha</label>
              
              <div class="row mb-3">
                <label for="date" class="col-md-4 col-form-label text-md-end">{{ __('Fecha') }}</label>
                <div class="col-md-6">
                    <input id="date" type="date" class="form-control" name="date" required autocomplete="date" autofocus>
                </div>
              </div>
              <button type="submit" class="btn btn-primary mb-2">Buscar</button>
            </form>
          </div>
        </div> 
      </div>
    </div>
  @endif
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card  border-primary mb-3">
                <div class="card-header border-primary text-center">{{ __('Sistema de Blogs') }}</div>

                <div class="card-body text-center">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    {{ Auth::user()->name }}  Ha iniciado Sesión!.
                </div>
                <div class="card-body text-center">
                    <a href="{{route('blog.index')}}" class="btn btn-primary">Ir a Gestión de Blogs</a>
                </div>

                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary shadow-sm ">
            <div class="container">
                <span class="navbar-brand mb-0 h1">Sistema de Blogs</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a href="{{route('blog.index')}}" class="nav-link"><span class="navbar-brand mb-0 h1">{{ __('Ver Blogs') }}</span></a>
                        </li>
                       
                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}"><span class="navbar-brand mb-0 h1">{{ __('Iniciar Sesión') }}</span></a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}"><span class="navbar-brand mb-0 h1">{{ __('Registrarse') }}</span></a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <span class="navbar-brand mb-0 h1"> {{ Auth::user()->name }} </span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cerrar Sesión') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>